### ISSUE TITLE
메인 화면 구현

### ISSUE THREAD

**Issue by jiwon2724** [jiwon2724/clean_architecture_practice_git_api#3]
### Description
MainActivity UI 구현

### Todo
 - [ ] 화면 UI 구현
 - [ ] visible, gone 애니메이션 처리
 - [ ] View 확장함수 개발
 - [ ] github api 연동
 - [ ] ViewModel 구현
